const captions = [
  "Life is better when you're laughing.",
  "You never know what you have until you have cleaned your house.",
  "Life is too short for bad vibes.",
  "Be the change you wish to see in the world.",
  "Life is like a camera, focus on the good times, develop from the negatives, and if things don't work out, take another shot.",
  "Life is too short to wear boring clothes.",
  "Be the reason someone smiles today.",
  "Believe in yourself and you will be unstoppable.",
  "Life is a journey, and if you fall in love with the journey, you will be in love forever.",
  "You are not a drop in the ocean. You are the entire ocean in a drop.",
  "Be yourself; everyone else is already taken.",
  "Life is not a problem to be solved, but a reality to be experienced.",
  "In the end, we only regret the chances we didn't take.",
  "The best way to predict your future is to create it.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "Life is short, enjoy every moment.",
  "Good things come to those who hustle.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Create your own sunshine.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Happiness is not something ready made. It comes from your own actions.",
  "In the middle of every difficulty lies opportunity.",
  "Life is a journey, not a destination.",
  "Believe you can and you're halfway there.",
  "Be the reason someone smiles today.",
  "Life is short, enjoy every moment.",
  "Good things come to those who hustle.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Create your own sunshine.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Happiness is not something ready made. It comes from your own actions.",
  "In the middle of every difficulty lies opportunity.",
  "Life is a journey, not a destination.",
  "Believe you can and you're halfway there.",
  "Be the reason someone smiles today.",
  "The best things in life are free.",
  "Happiness is a warm puppy.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "The only way to do great work is to love what you do.",
  "The best way to predict your future is to create it.",
  "If you can dream it, you can do it.",
  "The future is yours to create.",
  "Life is like a camera, focus on the good times, develop from the negatives, and if things don't work out, take another shot.",
  "Life is about creating yourself.",
  "Never give up on something that you can't go a day without thinking about.",
  "Don't wait for opportunity, create it.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The greatest wealth is to live content with little.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Life is a song, love is the music.",
  "Life is a canvas, paint it your way.",
  "Your future is created by what you do today, not tomorrow.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Dreams are like stars, you may never touch them, but if you follow them they will lead you to your destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You can't have a better tomorrow if you are thinking about yesterday all the time.",
  "The biggest adventure you can ever take is to live the life of your dreams.",
  "Don't let yesterday take up too much of today.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "The only way to have a good day is to start it with a positive attitude.",
  "Live life to the fullest and focus on the positive.",
  "Be the energy you want to attract.",
  "Your only limit is the amount of action you take.",
  "Be the change you wish to see in the world.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Don't wait for opportunities, create them.",
  "Life is a journey and only you hold the key.",
  "Be a voice, not an echo.",
  "The power of imagination makes us infinite.",
  "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it.",
];

const button = document.getElementById("generate-btn");
const output = document.getElementById("output");

button.addEventListener("click", function () {
  const randomIndex = Math.floor(Math.random() * captions.length);
  const randomCaption = captions[randomIndex];
  output.style.display = "block";
  output.textContent = randomCaption;
});
